DROP TABLE REVIEW;
DROP TABLE VISITEVENT;
DROP TABLE POITEM;
DROP TABLE PO;
DROP TABLE BOOK;
DROP TABLE USERINFO;
DROP TABLE ADDRESS;

CREATE TABLE ADDRESS (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
STREET VARCHAR(100) NOT NULL,
PROVINCE VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) NOT NULL,
ZIP VARCHAR(20) NOT NULL,
PHONE VARCHAR(20),
PRIMARY KEY(ID));

CREATE TABLE USERINFO (
UID VARCHAR(20) NOT NULL,
LNAME VARCHAR(20) NOT NULL,
FNAME VARCHAR(20) NOT NULL,
AID INTEGER NOT NULL,
EMAIL  VARCHAR(30) NOT NULL,
PWD VARCHAR(20) NOT NULL,
USERTYPE VARCHAR(20) CONSTRAINT USERTYPE_CK CHECK (USERTYPE IN ('Customer', 'Administrator', 'Partner')) NOT NULL,
PRIMARY KEY (UID),
FOREIGN KEY (AID) REFERENCES ADDRESS(ID)
);

CREATE TABLE BOOK 
(BID VARCHAR(20) NOT NULL, 
TITLE VARCHAR(60) NOT NULL,
PRICE INT NOT NULL,
CATEGORY VARCHAR(32) CONSTRAINT CATEGORY_CK CHECK (CATEGORY IN ('Science','Fiction','Engineering')) NOT NULL,
ARTWORK_URL VARCHAR(100) NOT NULL,
PRIMARY KEY(BID));

INSERT INTO BOOK (BID, TITLE, PRICE, CATEGORY, ARTWORK_URL) VALUES 
('b001', 'The Greatest Generation', 45, 'Fiction', 'image/The_Greatest_Generation.jpg'),
('b002', 'Vimy: The Battle and The Legend', 53, 'Fiction', '/image/Vimy.jpg'),
('b003', 'Animal Farm', 50, 'Fiction', '/image/Animal_Farm.jpg'),
('b004', 'The Outsider', 50, 'Science', '/image/The_Outsider.jpg'),
('b005', 'Fools and Mortals', 67, 'Engineering', '/image/Fools_and_Mortals.jpg'),
('b006', 'Absurd Thinking-Between Art and Design', 160, 'Science', 'image/Absurd Thinking-Between Art and Design.jpg'),
('b007', 'How to Draw Pokemon', 45, 'Engineering', 'image/How to Draw Pokemon.jpg'),
('b008', 'Pikachu in Love', 45, 'Fiction', 'image/Pikachu in Love.jpg');

CREATE TABLE PO (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
UID VARCHAR(20) NOT NULL,
DAY VARCHAR(12) NOT NULL,
LNAME VARCHAR(20) NOT NULL,
FNAME VARCHAR(20) NOT NULL,
STATUS VARCHAR(20) CONSTRAINT STATUS_CK CHECK (STATUS IN ('ORDERED','PROCESSED','DENIED')) NOT NULL,
ADDRESS INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (UID) REFERENCES USERINFO(UID),
FOREIGN KEY (ADDRESS) REFERENCES ADDRESS (ID) ON DELETE CASCADE
);

CREATE TABLE POItem (
ID INTEGER NOT NULL,
BID VARCHAR(20) NOT NULL,
PRICE INT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY (ID, BID),
FOREIGN KEY (ID) REFERENCES PO(ID) ON DELETE CASCADE,
FOREIGN KEY (BID) REFERENCES BOOK(BID) ON DELETE CASCADE
);

CREATE TABLE VISITEVENT (
DAY VARCHAR(12) NOT NULL,
BID VARCHAR(20) NOT NULL REFERENCES BOOK(BID),
EVENTTYPE  VARCHAR(20) CONSTRAINT EVENTTYPE_CK CHECK (EVENTTYPE IN ('VIEW','CART','PURCHASE')) NOT NULL,
FOREIGN KEY (BID) REFERENCES BOOK(BID)
);


CREATE TABLE REVIEW (
UID VARCHAR(20) NOT NULL,
BID VARCHAR(20) NOT NULL,
RATING INTEGER NOT NULL,
CONTENT VARCHAR(250) NOT NULL,
PRIMARY KEY (UID, BID),
FOREIGN KEY (UID) REFERENCES USERINFO(UID),
FOREIGN KEY (BID) REFERENCES BOOK(BID)
);

INSERT INTO Address (street, province, country, zip, phone) VALUES ('445 Avenue rd', 'ON', 'Canada', 'M1C 6K5' ,'416-123-8569')

/*the integer value '1' below for the administor is the address id of it, it is generate by the database itself, please makesure aid is corrrect */
INSERT into USERINFO values('eecs4413','Harry','Potter',1,'eecs4413@my.yorku.ca','weloveTAandProf','Administrator')
INSERT into USERINFO values('partner4413','Snow','White',1,'partner4413@my.yorku.ca','weloveTAandProf','Partner')

INSERT INTO Address (street, province, country, zip, phone) VALUES ('445 Avenue rd', 'ON', 'Canada', 'M1C 6K5' ,'416-123-8569')
INSERT into USERINFO values('Petter','Black','Petter',2,'petter@gmail.ca','123$q','Customer')

